name: ci-springboot-workflow
on:
  pull_request:
    branches:
      - dev
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: 21
    - name: Build with Maven
      run: mvn -B clean package -f pom.xml

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Listar conteúdo do diretório target
      run: ls -l target/

    - name: Copiar arquivo JAR para dentro do contexto de construção do Docker
      run: cp target/*.jar $GITHUB_WORKSPACE/target

    - name: Listar conteúdo do diretório Workspace do github
        run: ls -l $GITHUB_WORKSPACE/target/

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: mikaelmedeiros/ci-demo-java:latest



