name: ci-springboot-workflow
on:
  pull_request:
    branches:
      - dev
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: 21
    - name: Build with Maven
      run: mvn -B clean package -f pom.xml



